[pytest]
addopts =
    -p no:cacheprovider
    --benchmark-autosave
    --benchmark-min-rounds=1
    --benchmark-warmup=off
    --benchmark-sort=name
    --benchmark-columns=median,min,max,rounds
    --benchmark-name=short
filterwarnings =
    ignore:numpy.ndarray size changed:RuntimeWarning
