[pytest]
addopts =
    -p no:cacheprovider
    --benchmark-min-rounds=1
    --benchmark-warmup=off
    --benchmark-sort=name
    --benchmark-columns=median,min,max,rounds
    --benchmark-name=short
    --benchmark-group-by=func
    --benchmark-histogram=.benchmarks/plots/run
filterwarnings =
    ignore:numpy.ndarray size changed:RuntimeWarning
